name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-Build
      run: npm install && npm run build
    # 部署到 GitHub Pages
    - name: Vuepress-Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: zhq
        FOLDER: blog/.vuepress/dist
        CNAME: https://www.zhq.com
