# 工作流的名称，如果省略，则使用当前文件名
name: Auto Deploy

on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Code
      uses: actions/checkout@master
      with:
          # "最近更新时间"等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

    # 安装 Node 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        # 选择要使用的 node 版本
        node-version: '14'


    - name: Install
      run: yarn

    - name: Build
      run: yarn build 
    
    # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      # 环境变量
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
      with:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        BRANCH: zhq
        FOLDER: blog/.vuepress/dist
